---
# When username is defined get Spotify user authentication token
- name: Spotify user authentication
  spotify_auth:
    username: "{{ username }}"
    config_file: "{{ config_file }}"
  register: sp_user_auth
  when: username is defined

# When no username is defined get Spotify public authentication token
- name: Spotify public authentication
  spotify_auth:
    config_file: "{{ config_file }}"
  register: sp_public_auth
  when: username is undefined
