---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/user.yaml"
    auth_token: "{{ auth_token }}"
    username: bloch-m
    user_info_username: bloch
    user_info_output: full
    user_info_dest_file: "{{ playbook_dir }}/files/{{ username }}_user_info.json"
  environment:
    PYTHONPATH: "{{ playbook_dir }}/ansible/library/lib/spotipy_connection:{{ lookup('env','PYTHONPATH') }}"
  roles:
    - authentication
    - user_info
