---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/user.yaml"
    username: bloch-m
    get_user_playlists_for_user: "{{ username }}"
    get_user_playlists_output: short
    get_user_playlists_dest_file: "{{ playbook_dir }}/files/{{ username }}_playlists.json"
  environment:
    PYTHONPATH: "{{ playbook_dir }}/ansible/library/lib/spotipy_connection:{{ lookup('env','PYTHONPATH') }}"
  roles:
    - authentication
    - get_user_playlists
