---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/public.yaml"
    get_related_artists_for: young the giant
    get_related_dest_file: "{{ playbook_dir }}/files/related_artists.json"
    get_related_artists_output: full
    get_top_tracks_for_artists_name: Young the Giant
    get_top_tracks_for_country: AU
    get_top_tracks_output: full
    get_top_tracks_dest_file: "{{ playbook_dir }}/files/artists_top_tracks.json"
  environment:
    PYTHONPATH: "{{ playbook_dir }}/ansible/library/lib/spotipy_connection:{{ lookup('env','PYTHONPATH') }}"
  roles:
    - authentication
    - get_related_artists
    - { role: get_related_artists, get_related_artists_from_file: "{{get_related_dest_file}}" }
    - { role: get_artists_top_tracks, get_top_tracks_from_artists_file: "{{get_related_dest_file}}" }
