---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/user.yaml"
    username: bloch-m
    user_playlists_for_user: "{{ username }}"
    # user_playlists_state: get
    # user_playlists_output: full
    # user_playlists_dest_file: "{{ playbook_dir }}/files/{{ username }}_playlists.json"
    user_playlists_state: create
    user_playlists_name: ansible-playlist
    # user_playlists_public: no
  environment:
    PYTHONPATH: "{{ playbook_dir }}/ansible/library/lib/spotipy_connection:{{ lookup('env','PYTHONPATH') }}"
  roles:
    - authentication
    - user_playlists
