---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/public.yaml"
    auth_token: "{{ auth_token }}"
    get_top_tracks_for_artists_name: Young the Giant
    get_top_tracks_for_country: AU
    get_top_tracks_output: short
    get_top_tracks_dest_file: "{{ playbook_dir }}/files/artists_top_tracks.json"
    # get_top_tracks_from_artists_file: "{{ playbook_dir }}/files/related_artists.json"
  environment:
    PYTHONPATH: "{{ playbook_dir }}/ansible/library/lib/spotipy_connection:{{ lookup('env','PYTHONPATH') }}"
  roles:
    - authentication
    - get_artists_top_tracks
