---
# Get related artists from artists_name

- name: Get Users recently played somgs with default settings
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is undefined and user_tracks_dest_file is undefined and user_tracks_limit is undefined

- name: Get Users recently played somgs with defined output_format
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    output_format: "{{ user_tracks_output }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is defined and user_tracks_dest_file is undefined and user_tracks_limit is undefined

- name: Get Users recently played somgs with defined dest_file
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    dest_file: "{{ user_tracks_dest_file }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is undefined and user_tracks_dest_file is defined and user_tracks_limit is undefined


- name: Get Users recently played somgs with defined limit
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    limit: "{{ user_tracks_limit }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is undefined and user_tracks_dest_file is undefined and user_tracks_limit is defined

- name: Get Users recently played somgs with defined dest_file and output_format
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    output_format: "{{ user_tracks_output }}"
    dest_file: "{{ user_tracks_dest_file }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is defined and user_tracks_dest_file is defined and user_tracks_limit is undefined

- name: Get Users recently played somgs with defined limit and output_format
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    output_format: "{{ user_tracks_output }}"
    limit: "{{ user_tracks_limit }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is defined and user_tracks_dest_file is undefined and user_tracks_limit is defined

- name: Get Users recently played somgs with defined limit and output_format
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    dest_file: "{{ user_tracks_dest_file }}"
    limit: "{{ user_tracks_limit }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is undefined and user_tracks_dest_file is defined and user_tracks_limit is defined

- name: Get Users recently played somgs with defined limit and output_format
  spotify_user_tracks:
    auth_token: "{{ auth_token }}"
    output_format: "{{ user_tracks_output }}"
    dest_file: "{{ user_tracks_dest_file }}"
    limit: "{{ user_tracks_limit }}"
    state: "{{ user_tracks_state }}"
  when: user_tracks_output is defined and user_tracks_dest_file is defined and user_tracks_limit is defined
