---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/user.yaml"
    auth_token: "{{ auth_token }}"
    username: bloch-m
    user_playlists_for_user: "{{ username }}"
    user_playlists_state: search
    user_playlist_name: Like
    user_playlists_limit: 40
    user_playlists_output: long
    user_playlists_dest_file: "{{ playbook_dir }}/files/{{ username }}_playlists.json"
  roles:
    - authentication
    - user_playlists
