- name: Get related artists
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    # - name: Get related artists
    #   spotipy_related_artists:
    #     client_id: "{{ client_id }}"
    #     client_secret: "{{ client_secret }}"
    #     artist_name: young the giant
    #     limit: 5
    #     output_format: full
    #   environment:
    #     PYTHONPATH: "{{ playbook_dir }}/../library/lib:{{ lookup('env','PYTHONPATH') }}"

    # - name: Get related artists
    #   spotipy_related_artists:
    #     config_file: "{{playbook_dir}}/../inventory/group_vars/all.yaml"
    #     artist_name: young the giant
    #     dest_file: "{{playbook_dir}}/../artists.json"
    #     limit: 5
    #     output_format: short
    #   environment:
    #     PYTHONPATH: "{{ playbook_dir }}/../library/lib:{{ lookup('env','PYTHONPATH') }}"
    # #
    # - name: Get artists top tracks
    #   spotify_artists_top_tracks:
    #     config_file: "{{playbook_dir}}/../inventory/group_vars/all.yaml"
    #     # artists_uri: spotify:artist:3jOstUTkEu2JkjvRdBA5Gu
    #     artists_name: young the giant
    #     country: au
    #     dest_file: "{{playbook_dir}}/../artists_top_tracks.json"
    #     output_format: short
    #   environment:
    #     PYTHONPATH: "{{ playbook_dir }}/../library/lib:{{ lookup('env','PYTHONPATH') }}"

    # - name: Get user playlist
    #   spotipy_get_user_playlist:
    #     config_file: "{{playbook_dir}}/../inventory/group_vars/all.yaml"
    #     # artists_uri: spotify:artist:3jOstUTkEu2JkjvRdBA5Gu
    #     username: bloch-m
    #     output_format: full
    #   environment:
    #     PYTHONPATH: "{{ playbook_dir }}/../library/lib/spotipy_connection:{{ lookup('env','PYTHONPATH') }}"
