---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/user.yaml"
    username: bloch-m
    user_info_output: long
    # user_info_limit: 59
    # user_info_dest_file: "{{ playbook_dir }}/../files/{{ username }}_top_artists.json"
    user_info_state: top_artists
    # user_info_time_range: medium_term
  roles:
    - authentication
    - user_info
