---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/user.yaml"
    auth_token: "{{ auth_token }}"
    username: bloch-m
    user_info_state: devices
    user_info_output: short
    user_info_dest_file: "{{ playbook_dir }}/../files/{{ username }}_user_info.json"
  roles:
    - authentication
    - user_info
