---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/public.yaml"
    auth_token: "{{ auth_token }}"
    track_data_state: analyse
    track_data_dest_file: "{{ playbook_dir }}/../files/track_data_{{ track_data_state }}_file.json"
    track_data_track_file: "{{ playbook_dir }}/../files/bloch-m_top_tracks.json"
  roles:
    - authentication
    - track_data
