---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/public.yaml"
    search_for: artists
    search_for_artists_name: Young the Giant
    search_result_output: short
    search_result_limit: 20
  roles:
    - authentication
    - search
