---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/public.yaml"
    auth_token: "{{ auth_token }}"
    search_for: artists_and_albums
    search_for_artists_name: The xx
    search_for_albums_name: Coexist
    search_result_output: short
    search_result_limit: 20
    search_dest_file: "{{ playbook_dir }}/../files/search_result_{{ search_for }}.json"
  roles:
    - authentication
    - search
