---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/public.yaml"
    auth_token: "{{ auth_token }}"
    search_for: playlists
    search_for_playlists_name: Colombia*
    search_result_output: long
    search_result_limit: 40
    search_dest_file: "{{ playbook_dir }}/../files/search_result_{{ search_for }}.json"
  roles:
    - authentication
    - search
