---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/user.yaml"
    auth_token: "{{ auth_token }}"
    username: bloch-m
    user_tracks_output: short
    user_tracks_limit: 10
    user_tracks_dest_file: "{{ playbook_dir }}/files/{{ username }}_user_info.json"
    user_tracks_state: top_artists
    user_tracks_time_range: medium_term
  roles:
    - authentication
    - user_tracks
