---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    config_file: "{{inventory_dir}}/group_vars/public.yaml"
    auth_token: "{{ auth_token }}"
    get_related_artists_for: young the giant
    # get_related_artists_from_file:  "{{ playbook_dir }}/files/search_result_artists.json"
    get_related_dest_file: "{{ playbook_dir }}/files/related_artists.json"
  roles:
    - authentication
    - get_related_artists
