---
- import_tasks: create.yaml
  when: user_playlists_state == "create"
- import_tasks: get_all.yaml
  when: user_playlists_state == "get_all"
- import_tasks: search.yaml
  when: user_playlists_state == "search"
